# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#                                                       1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibbonacci():
    first_num = 1
    second_num = 2
    sequence = [1, 2]
    even_terms = []
    
    while len(sequence):
        first_num += second_num
        second_num += first_num
        if first_num >= 4000000:
            break
        sequence.append(first_num)
        sequence.append(second_num)
        
    #print(sequence)
        
    for i in sequence:
        if i % 2 == 0:
            even_terms.append(i)
            
    print(sum(even_terms))
        

fibbonacci()